jwt:
  secret: secretKey-local-jwt-for-mysteam-project

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/steam
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      format_sql: true
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "caches"