jwt:
  secret: secretKey-local-jwt-for-mysteam-project

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/steam
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

management:
  endpoints:
    web:
      exposure:
        include: "caches"